#macro Lorem "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas efficitur neque vitae dolor commodo, vitae pretium massa tincidunt. Cras non mattis elit. Quisque finibus ligula turpis, et placerat erat efficitur eget. Quisque ex justo, scelerisque ac dignissim nec, malesuada vel quam. Etiam ut felis arcu. Nulla facilisi. Etiam euismod viverra lectus, quis gravida eros iaculis id. Nullam gravida, augue id efficitur ullamcorper, nulla ligula commodo metus, in ultrices erat ante a velit. In vehicula mollis justo, et luctus dolor. Nullam nec efficitur nibh. Maecenas sagittis sem vitae mi rutrum, ac mattis eros molestie. Etiam elit magna, pharetra eu accumsan non, cursus in turpis. Pellentesque in fermentum mi, nec fermentum elit."

global.game_uis = {};

global.game_uis.main_menu = {
  "name":"main_panel",
  "left":275.0,
  "top":50.0,
  "width":1280.0,
  "data":{
    "image":"sTitle"
  },
  "height":720.0,
  "nodes":[
    {
      "name":"top_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel1"
        },
        {
          "margin":0.0,
          "name":"grid_panel2",
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        },
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel3"
        }
      ]
    },
    {
      "name":"middle_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel4"
        },
        {
          "margin":0.0,
          "name":"grid_panel5",
          "flexDirection":"row",
          "border":0.0,
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
            "image":""
          }
        },
        {
          "name":"grid_panel6",
          "flexBasis":0.0,
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        }
      ]
    },
    {
      "name":"bottom_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "margin":0.0,
          "name":"grid_panel7",
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        },
        {
          "name":"grid_panel8",
          "flexDirection":"row",
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "nodes":[
            {
              "name":"panel_68989",
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "height":60.0
            },
            {
              "name":"menu_options",
              "flex":4.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "marginTop":-43.0,
              "marginBottom":128.0
            },
            {
              "name":"panel_39867",
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "height":60.0
            }
          ]
        },
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel9"
        }
      ]
    }
  ]
}
