#macro Lorem "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas efficitur neque vitae dolor commodo, vitae pretium massa tincidunt. Cras non mattis elit. Quisque finibus ligula turpis, et placerat erat efficitur eget. Quisque ex justo, scelerisque ac dignissim nec, malesuada vel quam. Etiam ut felis arcu. Nulla facilisi. Etiam euismod viverra lectus, quis gravida eros iaculis id. Nullam gravida, augue id efficitur ullamcorper, nulla ligula commodo metus, in ultrices erat ante a velit. In vehicula mollis justo, et luctus dolor. Nullam nec efficitur nibh. Maecenas sagittis sem vitae mi rutrum, ac mattis eros molestie. Etiam elit magna, pharetra eu accumsan non, cursus in turpis. Pellentesque in fermentum mi, nec fermentum elit."

global.game_uis = {};

global.game_uis.main_menu = {
  "name":"main_panel",
  "left":275.0,
  "top":50.0,
  "width":1280.0,
  "data":{
  },
  "height":720.0,
  "nodes":[
    {
      "name":"top_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel1"
        },
        {
          "margin":0.0,
          "name":"grid_panel2",
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        },
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel3"
        }
      ]
    },
    {
      "name":"middle_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel4"
        },
        {
          "margin":0.0,
          "name":"grid_panel5",
          "flexDirection":"row",
          "border":0.0,
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
            "image":""
          }
        },
        {
          "name":"grid_panel6",
          "flexBasis":0.0,
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        }
      ]
    },
    {
      "name":"bottom_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "margin":0.0,
          "name":"grid_panel7",
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        },
        {
          "name":"grid_panel8",
          "flexDirection":"row",
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "nodes":[
            {
              "name":"panel_68989",
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "height":60.0
            },
            {
              "name":"menu_options",
              "flex":4.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "marginTop":-43.0,
              "marginBottom":128.0
            },
            {
              "name":"panel_39867",
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "height":60.0
            }
          ]
        },
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel9"
        }
      ]
    }
  ]
}

global.game_uis.rooms = {
  "name":"main_panel",
  "left":275.0,
  "top":50.0,
  "width":1280.0,
  "data":{
    "image":"sJoin"
  },
  "height":720.0,
  "nodes":[
    {
      "name":"top_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel1"
        },
        {
          "name":"grid_panel2",
          "margin":0.0,
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        },
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel3"
        }
      ]
    },
    {
      "name":"middle_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel4"
        },
        {
          "name":"grid_panel5",
          "margin":0.0,
          "minWidth":515.0,
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "border":0.0,
          "nodes":[
            {
              "marginBottom":0.0,
              "maxHeight":361.0,
              "name":"join_panel",
              "flex":1.0,
              "padding":10.0,
              "minHeight":435.0,
              "data":{
              },
              "nodes":[
                {
                  "padding":0.0,
                  "width":60.0,
                  "data":{
                  },
                  "height":16.0,
                  "name":"join_label"
                },
                {
                  "name":"code_panel",
                  "flexDirection":"row",
                  "padding":10.0,
                  "data":{
                  },
                  "height":41.0,
                  "nodes":[
                    {
                      "name":"code_label",
                      "flex":1.0,
                      "padding":10.0,
                      "width":60.0,
                      "data":{
                      },
                      "height":25.0
                    },
                    {
                      "name":"spacer",
                      "flex":1.0,
                      "padding":10.0,
                      "width":60.0,
                      "data":{
                      },
                      "height":25.0
                    },
                    {
                      "name":"code_input",
                      "top":0.0,
                      "width":152.0,
                      "data":{
                      },
                      "height":25.0,
                      "marginLeft":0.0,
                      "marginRight":4.0
                    },
                    {
                      "top":0.0,
                      "width":160.0,
                      "data":{
                      },
                      "height":25.0,
                      "name":"join_button"
                    }
                  ],
                  "marginTop":14.0,
                  "marginBottom":0.0
                },
                {
                  "name":"panel_51891",
                  "flexDirection":"row",
                  "flex":1.0,
                  "padding":0.0,
                  "data":{
                  },
                  "height":60.0,
                  "nodes":[
                    {
                      "name":"filters",
                      "minWidth":211.0,
                      "padding":10.0,
                      "width":60.0,
                      "data":{
                      },
                      "marginTop":10.0
                    },
                    {
                      "marginTop":10.0,
                      "name":"room_panel",
                      "flex":1.0,
                      "padding":10.0,
                      "width":60.0,
                      "data":{
                      },
                      "marginLeft":5.0,
                      "nodes":[
                        {
                          "flex":1.0,
                          "padding":10.0,
                          "data":{
                          },
                          "name":"room_list",
                          "marginRight":12.0
                        }
                      ]
                    }
                  ]
                }
              ],
              "marginTop":-98.0
            }
          ]
        },
        {
          "name":"grid_panel6",
          "flex":1.0,
          "flexBasis":0.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        }
      ]
    },
    {
      "name":"bottom_panel_grid",
      "flexDirection":"row",
      "left":0.0,
      "flex":1.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "nodes":[
        {
          "name":"grid_panel7",
          "margin":0.0,
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        },
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel8"
        },
        {
          "flex":1.0,
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "name":"grid_panel9"
        }
      ]
    }
  ]
}