scribble_font_set_default("Font3");
x = 10;
y = 10;
count = 0;
lastroom = "test";
AirNet[$ "connection"] ??= new connection(AirNet.ip, AirNet.port, network_socket_udp);
AirNet.connection.connect();
AirNet.host = false;
AirNet.players_in_room = [];
mx = mouse_x;
my = mouse_y;
room_code = undefined;
dbglog = false;
depth = 1000;