#macro AirLib global.__air
#macro AirLibDefaultStyle AirLibBtnStyle.Rounded //Default, Rounded, Flat
#macro AirLibDefaultBGSprite sButton
#macro AirLibTags ["bg", "fg", "button", "input"]
AirLib = {
    frame : 0,
    listframe : 0,
    lib_uis : {}
 }

AirLib.lib_uis.tag_manager = {
  "name":"main_panel",
  "left":275.0,
  "padding":10.0,
  "top":50.0,
  "width":400.0,
  "data":{
    "tags":[
      "bg"
    ]
  },
  "height":300.0,
  "nodes":[
    {
      "padding":10.0,
      "data":{
      },
      "height":30.0,
      "name":"title"
    },
    {
      "name":"body_panel",
      "flex":1.0,
      "padding":10.0,
      "data":{
        "tags":[
          "fg"
        ]
      },
      "height":60.0,
      "nodes":[
        {
          "name":"tags_panel",
          "flex":1.0,
          "padding":10.0,
          "data":{
          },
          "height":60.0,
          "nodes":[
            {
              "name":"spacer4",
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "height":60.0
            },
            {
              "flexDirection":"row",
              "name":"tag_drop_panel",
              "padding":0.0,
              "data":{
              },
              "height":60.0,
              "nodes":[
                {
                  "flex":1.0,
                  "padding":10.0,
                  "width":60.0,
                  "data":{
                  },
                  "name":"tags_label"
                },
                {
                  "flex":1.0,
                  "padding":10.0,
                  "width":60.0,
                  "data":{
                  },
                  "name":"dropdown_tags"
                }
              ]
            },
            {
              "name":"spacer5",
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "height":60.0
            }
          ]
        },
        {
          "flexDirection":"row",
          "name":"btn_panel",
          "padding":10.0,
          "data":{
          },
          "height":60.0,
          "nodes":[
            {
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "name":"spacer1"
            },
            {
              "flex":2.0,
              "padding":10.0,
              "width":61.0,
              "data":{
                "tags":[
                  "button"
                ]
              },
              "name":"button_accept"
            },
            {
              "flex":1.0,
              "padding":10.0,
              "data":{
              },
              "name":"spacer2"
            },
            {
              "flex":2.0,
              "padding":10.0,
              "width":60.0,
              "data":{
                "tags":[
                  "button"
                ]
              },
              "name":"button_cancel"
            },
            {
              "flex":1.0,
              "padding":10.0,
              "width":60.0,
              "data":{
              },
              "name":"spacer3"
            }
          ]
        }
      ]
    }
  ]
}
