ui = new window(global.game_uis.rooms);
ui.fit_to_gui();
roundness_x = 10;
roundness_y = 15;
room_list_offset = 53;
room_list_h = 50;
room_list_title_x = 15;
room_list_title_y = 5;
room_list_title_scale = 1;
room_list_btn_x = 120;
room_list_btn_y = 10;
room_list_btn_w = 110;
room_list_btn_h = 32;
room_list_scroll = 0;
scrolltime = 0;
code_input = new textbox();
code_input.only_numbers = true;
code_input.textcolor = "c_white";
code_input.only_numbers = false;
code_input.backspr = undefined;
code_input.backtext = "Code Here";
code_button = new button("Join Lobby");
code_button.set_function(method(self, function() {
	new packet("joinCode").write("roomCode", code_input.text).send();
}));
bg = #FFEED5;
fg = #D5AA73;
//room_list_ = ;
//room_list_ = ;
roomsurf = undefined;
dbg = dbg_view("Join", false, 10, 10);
create_view_from_instance(self);
room_list = undefined;

new packet("getRoomList").send();