/// @description Insert description here
// You can write your code in this editor
ui = new window({
  "name":"main_panel",
  "nodes":[
    {
      "flex":1.0,
      "name":"top_panel_grid",
      "nodes":[
        {
          "padding":0.0,
          "width":60.0,
          "flex":1.0,
          "data":{
          },
          "name":"grid_panel1"
        },
        {
          "flex":1.0,
          "name":"grid_panel2",
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "margin":0.0
        },
        {
          "padding":0.0,
          "width":60.0,
          "flex":1.0,
          "data":{
          },
          "name":"grid_panel3"
        }
      ],
      "left":0.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "flexDirection":"row"
    },
    {
      "flex":1.0,
      "name":"middle_panel_grid",
      "nodes":[
        {
          "flex":1.0,
          "name":"grid_panel4",
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "margin":0.0
        },
        {
          "alignItems":"center",
          "flex":1.0,
          "name":"grid_panel5",
          "border":0.0,
          "nodes":[
            {
              "name":"login_panel",
              "nodes":[
                {
                  "padding":10.0,
                  "data":{
                    "tags":[
                      "fg"
                    ]
                  },
                  "height":25.0,
                  "name":"title",
                  "margin":5.0
                },
                {
                  "flex":1.0,
                  "name":"body_panel",
                  "nodes":[
                    {
                      "flex":1.0,
                      "name":"user_label",
                      "padding":10.0,
                      "width":60.0,
                      "data":{
                      },
                      "height":60.0,
                      "alignSelf":"center"
                    },
                    {
                      "padding":10.0,
                      "data":{
                        "tags":[
                          "input"
                        ]
                      },
                      "height":60.0,
                      "name":"username"
                    },
                    {
                      "flex":1.0,
                      "name":"pass_label",
                      "marginTop":5.0,
                      "padding":10.0,
                      "width":60.0,
                      "minHeight":0.0,
                      "data":{
                      },
                      "height":60.0,
                      "alignSelf":"center"
                    },
                    {
                      "padding":10.0,
                      "data":{
                        "tags":[
                          "input"
                        ]
                      },
                      "height":60.0,
                      "name":"password"
                    },
                    {
                      "name":"btn_panel",
                      "nodes":[
                        {
                          "padding":10.0,
                          "width":60.0,
                          "flex":1.0,
                          "data":{
                          },
                          "name":"spacer1"
                        },
                        {
                          "padding":10.0,
                          "width":60.0,
                          "flex":3.0,
                          "data":{
                            "tags":[
                              "button"
                            ]
                          },
                          "name":"login"
                        },
                        {
                          "flex":1.0,
                          "name":"spacer3",
                          "padding":10.0,
                          "width":60.0,
                          "data":{
                          },
                          "height":60.0
                        },
                        {
                          "padding":10.0,
                          "width":60.0,
                          "flex":3.0,
                          "data":{
                            "tags":[
                              "button"
                            ]
                          },
                          "name":"register"
                        },
                        {
                          "padding":10.0,
                          "width":60.0,
                          "flex":1.0,
                          "data":{
                          },
                          "name":"spacer2"
                        }
                      ],
                      "left":0.0,
                      "padding":5.0,
                      "data":{
                      },
                      "height":60.0,
                      "flexDirection":"row"
                    }
                  ],
                  "padding":10.0,
                  "data":{
                  },
                  "height":60.0
                }
              ],
              "padding":0.0,
              "top":-30.0,
              "width":450.0,
              "data":{
                "tags":[
                  "bg"
                ]
              },
              "height":300.0,
              "alignSelf":"center"
            }
          ],
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "margin":0.0
        },
        {
          "flexBasis":0.0,
          "flex":1.0,
          "name":"grid_panel6",
          "padding":0.0,
          "width":60.0,
          "data":{
          }
        }
      ],
      "left":0.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "flexDirection":"row"
    },
    {
      "flex":1.0,
      "name":"bottom_panel_grid",
      "nodes":[
        {
          "flex":1.0,
          "name":"grid_panel7",
          "padding":0.0,
          "width":60.0,
          "data":{
          },
          "margin":0.0
        },
        {
          "padding":0.0,
          "width":60.0,
          "flex":1.0,
          "data":{
          },
          "name":"grid_panel8"
        },
        {
          "padding":0.0,
          "width":60.0,
          "flex":1.0,
          "data":{
          },
          "name":"grid_panel9"
        }
      ],
      "left":0.0,
      "padding":0.0,
      "top":0.0,
      "data":{
      },
      "height":300.0,
      "flexDirection":"row"
    }
  ],
  "left":275.0,
  "top":50.0,
  "width":1280.0,
  "data":{
  },
  "height":720.0
})
ui.fit_to_gui();
username = new textbox();
username.set_align(fa_center, fa_middle);
username.backtext = "username";
password = new textbox();
password.set_align(fa_center, fa_middle);
password.backtext = "password";
login = new button("Login");
login.set_function(method(self, function() {
	new packet("login")
	.write("username", username.text)
	.write("passwordhash", sha1_string_unicode(password.text))
	.send();
}));
register = new button("Register");
register.set_function(method(self, function() {
	new packet("register")
	.write("username", username.text)
	.write("passwordhash", sha1_string_unicode(password.text))
	.send();
}));